set_constant(:IS_CONFIGURED, true)
set_constant(:PRETTY_SITE_NAME, "Kete")
set_constant(:SITE_NAME, "www.example.com")
set_constant(:SITE_URL, "http://www.example.com/") # webrat relies on www.example.com
set_constant(:NOTIFIER_EMAIL, "user@changeme.com")
set_constant(:CONTACT_EMAIL, "user@changeme.com")
set_constant(:RECORDS_PER_PAGE_CHOICES, [5, 10, 20, 50])
set_constant(:DEFAULT_RECORDS_PER_PAGE, 5)
set_constant(:DEFAULT_SEARCH_CLASS, "Topic")
set_constant(:NUMBER_OF_RELATED_THINGS_TO_DISPLAY_PER_TYPE, 5)
set_constant(:NUMBER_OF_RELATED_IMAGES_TO_DISPLAY, 5)
set_constant(:DEFAULT_NUMBER_OF_MULTIPLES, 5)
set_constant(:FLAGGING_TAGS, ['inaccurate', 'duplicate', 'inappropriate', 'entered by mistake', 'has typos'])
set_constant(:LEGACY_IMAGEFILE_PATHS_UP_TO, 0)
set_constant(:LEGACY_AUDIORECORDING_PATHS_UP_TO, 0)
set_constant(:LEGACY_DOCUMENT_PATHS_UP_TO, 0)
set_constant(:LEGACY_VIDEO_PATHS_UP_TO, 0)
set_constant(:REQUIRE_ACTIVATION, false)
set_constant(:ABOUT_BASKET, 3)
set_constant(:HELP_BASKET, 2)
set_constant(:EXTENDED_FIELD_FOR_USER_NAME, "user_name")
set_constant(:DOWNLOAD_WARNING, "You are about to download a file from Kete. Kete is an open digital repository and as such we can not guarantee the integrity of any file in the repository.  Please ensure that your virus scan software is operating and is configured to scan this download.\n                                                                                                                                                                                                                                                          Are you sure you want to proceed?")
set_constant(:TAGS_SYNONYMS, nil)
set_constant(:DESCRIPTION_SYNONYMS, nil)
set_constant(:DESCRIPTION_TEMPLATE, nil)
set_constant(:IMAGE_SIZES, {:small_sq => '50x50!', :small => '50', :medium => '200>', :large => '400>'})
set_constant(:IMAGE_CONTENT_TYPES, ['image/tiff', 'image/bmp', 'image/x-ms-bmp', 'image/quicktime', 'image/x-quicktime', 'application/postscript', :image])
set_constant(:MAXIMUM_UPLOADED_FILE_SIZE, 52428800)
set_constant(:DOCUMENT_CONTENT_TYPES, ['text/html', 'text/plain', 'text/rtf', 'text/css', 'application/mac-binhex40', 'application/msword', 'application/word', 'application/pdf', 'application/pics-rules', 'application/postscript', 'application/rtf', 'application/vnd.ms-excel', 'application/vnd.ms-powerpoint', 'application/x-gtar', 'application/x-gzip', 'application/zip', 'application/x-zip', 'application/x-zip-compressed', 'application/x-tar', 'application/x-compressed-tar', 'application/vnd.oasis.opendocument.chart', 'application/vnd.oasis.opendocument.database', 'application/vnd.oasis.opendocument.formula', 'application/vnd.oasis.opendocument.drawing', 'application/vnd.oasis.opendocument.image', 'application/vnd.oasis.opendocument.text-master', 'application/vnd.oasis.opendocument.presentation', 'application/vnd.oasis.opendocument.spreadsheet', 'application/vnd.oasis.opendocument.text', 'application/vnd.oasis.opendocument.text-web', 'image/jpeg', 'image/jpg'])
set_constant(:AUDIO_CONTENT_TYPES, ['audio/mpeg', 'audio/mpg', 'audio/x-mpeg', 'audio/x-mpegurl', 'audio/wav', 'audio/x-wav', 'audio/x-ms-wma', 'audio/x-ms-waxaudio', 'application/ogg', 'audio/x-vorbis+ogg', 'audio/x-aiff'])
set_constant(:VIDEO_CONTENT_TYPES, ['application/x-shockwave-flash', 'application/flash-video', 'application/x-flash-video', 'video/x-flv', 'video/mp4', 'video/x-m4v', 'video/mpeg', 'video/quicktime', 'video/x-msvideo', 'video/avi', 'video/x-quicktime', 'application/x-director', 'image/mov', 'application/asx', 'video/x-ms-asf-plugin', 'application/x-mplayer2', 'video/x-ms-asf', 'video/x-ms-wm', 'video/x-ms-wmv', 'video/x-ms-wvx', 'application/x-dvi'])
set_constant(:SETUP_SECTIONS, ['Server', 'System', 'Accounts', 'Warnings', 'Flagging', 'Results Display', 'Related Items Display', 'Extended Fields'])
set_constant(:DOCUMENTATION_BASKET, 4)
set_constant(:ENABLE_CONVERTING_DOCUMENTS, false)
set_constant(:DEFAULT_POLICY_IS_FULL_MODERATION, false)
set_constant(:BLANK_TITLE, "Pending Moderation")
set_constant(:PENDING_FLAG, "pending")
set_constant(:REJECTED_FLAG, "rejected")
set_constant(:BLANK_FLAG, "used for moderation")
set_constant(:REVIEWED_FLAG, "reviewed by moderator")
set_constant(:FREQUENCY_OF_MODERATION_EMAIL, 4)
set_constant(:TITLE_SYNONYMS, nil)
set_constant(:SHORT_SUMMARY_SYNONYMS, nil)
set_constant(:IMPORT_FIELDS_TO_IGNORE, ['HiliteLibrary'])
set_constant(:DEFAULT_BASKETS_IDS, [1])
set_constant(:CAPTCHA_TYPE, "all")
set_constant(:DEFAULT_CONTENT_LICENSE, "")
set_constant(:FORCE_HTTPS_ON_RESTRICTED_PAGES, false)
set_constant(:NO_PUBLIC_VERSION_TITLE, "No Public Version Available")
set_constant(:NO_PUBLIC_VERSION_DESCRIPTION, "There is currently no public version of this item.")
set_constant(:PROVIDE_OAI_PMH_REPOSITORY, false)
set_constant(:USES_BASKET_LIST_NAVIGATION_MENU_ON_EVERY_PAGE, false)
set_constant(:AVAILABLE_SYNTAX_HIGHLIGHTERS, [])
set_constant(:GOVERNMENT_WEBSITE, "")
set_constant(:DEFAULT_PAGE_KEYWORDS, "kete,topics,images,audio,video,web links,documents,discussion,community")
set_constant(:DEFAULT_PAGE_DESCRIPTION, "Kete is a knowledge basket of topics, images, audio, video, web links, documents, and discussion which are collected and catalogued by the community.")
set_constant(:ENABLE_USER_PORTRAITS, false)
set_constant(:ENABLE_GRAVATAR_SUPPORT, false)
set_constant(:BASKET_CREATION_POLICY, "closed")
