language: ruby
cache: bundler
bundler_args: --without development
before_install:
  - gem install bundler
rvm:
  - 2.3.3
before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load
  - bundle exec bundle-audit update
  - npm install
script:
  - bundle exec rspec spec
  # - bundle exec rubocop
  - bundle exec bundle-audit check
  - ./node_modules/.bin/grunt
